Merge feature/token-experiment to master and make default style to use 2.5 (#3887)
* Initial check-in for colors/brushes, preliminary button brush updates, and adding visual states test page (#3514)

* add visual states test page

* add visual states test page

* Add new colors, update Button* brushes

* Tweaked CSV, added accent button

* Fix bad merge

* Added elevation border brushes

* Temporarily disable failing tests so other work can be unblocked.

* merge master into feature branch (#3556)

* Move build to windevbuildagents (#3511)

* Remove infobar from innerloop when it isn't explicitly included. (#3512)

* Remove infobar from innerloop when it isn't explicitly included.

* Update InnerLoopAreas.props

Remove feature area from InnerLoopAreas

* add condition

* revert innerloop solution file

* revert innerloop solution file

* Update script to add API test projects and add empty dependency list in FeatureArea.props file (#3474)

* Update new control script to add API test project

* Update script to add dependencies, clean up script

* * Rename FindElementOfTypeInSubtree  -> FindVisualChildByType (#3438)

* FindVisualChildByName() now an extension method

* internal code cleanup

* IsSelectionRequried -> IsSelectionRequired (#3404)

* IsSelectionRequried -> IsSelectionRequired

* TreeViewListAutomationPeer::IsSelectionRequired() always returns false.

* Update the test infra to account for the test app having a different name when built from the inner loop solution. (#3359)

* Feature/expander (#3492)

Adding expander control (#3492).

Co-authored-by: Keith Mahoney <41657372+kmahone@users.noreply.github.com>
Co-authored-by: Stephen L Peters <stpete@microsoft.com>
Co-authored-by: Marcel Wagner <marcel.alex.wagner@outlook.com>
Co-authored-by: Felix-Dev <FelixDev91@gmail.com>
Co-authored-by: Tony Xia <xia_tony@hotmail.com>
Co-authored-by: EJ <lalotahoma@icloud.com>

* update controls to use design token colors, update styles (#3728)

* merge master into feature branch (#3734)

* Move build to windevbuildagents (#3511)

* Remove infobar from innerloop when it isn't explicitly included. (#3512)

* Remove infobar from innerloop when it isn't explicitly included.

* Update InnerLoopAreas.props

Remove feature area from InnerLoopAreas

* add condition

* revert innerloop solution file

* revert innerloop solution file

* Update script to add API test projects and add empty dependency list in FeatureArea.props file (#3474)

* Update new control script to add API test project

* Update script to add dependencies, clean up script

* * Rename FindElementOfTypeInSubtree  -> FindVisualChildByType (#3438)

* FindVisualChildByName() now an extension method

* internal code cleanup

* IsSelectionRequried -> IsSelectionRequired (#3404)

* IsSelectionRequried -> IsSelectionRequired

* TreeViewListAutomationPeer::IsSelectionRequired() always returns false.

* Update the test infra to account for the test app having a different name when built from the inner loop solution. (#3359)

* Feature/expander (#3492)

Adding expander control (#3492).

* Initial check-in for colors/brushes, preliminary button brush updates, and adding visual states test page (#3514)

* add visual states test page

* add visual states test page

* Add new colors, update Button* brushes

* Tweaked CSV, added accent button

* Fix bad merge

* Added elevation border brushes

* Temporarily disable failing tests so other work can be unblocked.

* NavView: Fix CornerRadius for overflow menu and NavViewItem children flyout menu (#3082)

* Fix corner radius for the overflow menu and the children flyout menu.

* Add two interaction tests.

* Small comment improvements.

* Small comment improvement.

* Move top NavigationView specific overflow button tests from CommonTests to TopModeTests.

* Now close opened flyout in API test before finishing.

* Rename FindElementOfTypeInParentTree  -> FindVisualParentByType

* Add missing resource files to LocConfig (#3567)

* Cache IsFullScreenMode and invalidate the value only when SizeChanged is raised (#3569)

* Fix issue with ProgressRing not acting correctly when moving backwards (#3565)

* Add workaround for awkward progress ring behavior.

* Update progresring backwards behavior

* move pager resources under strings/en-us folder (#3593)

* make footer menu items public (#3519)

* update progress ring idl (#3599)

* TabView: Fix newly-added items not respecting TabWidthMode [compact] when using an ItemsSource collection (#3118)

* Fix the following issues when populating the TabView via its ItemsSource API:
* crash when clearing the ItemsSource
* TabWidthMode [compact] being ignored in XAML Markup and for newly-added items

* small comment improvement

* Added two API tests and modified existing test.

* Unrelated code which was commented out is run again.

* Add API test.

* Simplified API test.

* Merge API tests.

* Add API contract checks for corner radius.

* Ensure that listview selected index is not outside of the item range.

* Update TabView.cpp

Co-authored-by: Ranjesh <28935693+ranjeshj@users.noreply.github.com>

* Switch to using ThemeResource for icon in InfoBar (#3603)

* Allow winui to detect if it's in CBS package (#3520)

* build cbs

* Revert "build cbs"

This reverts commit 24b6812d266b84a56336b89000c8ddc4b6e14b0a.

* cbs:

* Update dev/dll/SharedHelpers.cpp

Co-authored-by: Jevan Saks <jevansa@microsoft.com>

* Update dev/dll/XamlControlsResources.cpp

Co-authored-by: Jevan Saks <jevansa@microsoft.com>

* remove check for old platform and add assert

* make pipeline build cbs resources.pri and manifest

* Update dev/dll/XamlControlsResources.cpp

* Update dev/dll/XamlControlsResources.cpp

* fail fast

* Update dev/dll/XamlControlsResources.cpp

* fix package name when generate CBSManifest

Co-authored-by: Jevan Saks <jevansa@microsoft.com>

* Doc/roadmap updates (#3618)

* Updating ordering

* Updating feature roadmap

* More updates to feature roadmap, roadmap graphic

* Update bug_report.md (#3622)

* Fix readme to mention Preview 3 instead of P2 (#3621)

* Update NavigationView pane scrolling behavior (#3602)

* Add initial layout updating, add test page

* Add first interaction tests

* Fix behavior, add scrolling behavior

* CR feedback

* Add hacky workaround for weird sizing behavior

* Update layout, add separator

* Fix updating behavior

* Remove hacky workaround, fix test

* Add fault tolerance to tests

* Update verification files

* Change Preview 2 to Preview 3 (#3626)

* Update preview_upgrade_instructions.md (#3636)

* TeachingTip: Fix background for light-dismissable tip (#3440)

* Add missing visual state setters.

* Extend API test.

* update loc strings (#3650)

* File Pipeline build break: Update Nuget from 5.2 to 5.8 (#3664)

* Fixing an issue where we needed a FileWrites to avoid file deletion. (#3661)

* Remove explicit sizes of InfoBar (#3653)

* Remove explicit sizes of InfoBar

* Set minheight for centering

* Switch to lightweight styling resources

* Update CommandBarFlyout closing animation to include button moving (#3594)

* Update more-button animation behavior

* Fix background issue

* CR feedback

* update intellisense file (#3651)

* Update AcrylicBrushes and add new AcrylicBrushes (#3498)

* Add new brushes, update CommandbarFlyout and NavigationView to use new brushes

* Update brushes

* Update brush references

* Update project file

* Update navigationview resources

* Hacky workaround XAML compiler bug

* Add check

* Add comment

* Fix typo

* Add ImageIcon (#3629)

* Add ImageIcon

* Respond to feedback and use an svg image with an MIT license.

* Fix broken test

* Platform check the IsLoaded check which was introduced in RS5

* Fix Innerloop Solution (#3697)

* Add ImageIcon

* Respond to feedback and use an svg image with an MIT license.

* Fix broken test

* Platform check the IsLoaded check which was introduced in RS5

* Add preprocessor declaration around imageIconSource code in MakeIconElementFrom

* Update InfoBarPanel API names (#3704)

* Update API names

* Remove grid.columns

* Adding PipsPager  (#3592)

* PipsControl initial structure

* PipsControl update file structure

* Add boilerplate code

* Add styles and update logic

* Remove Grid inside the PipsControl

* some layout fixes

* Update common styles

* Fix nav buttons visibility logic

* Update themeresources and fix infinite scrolling

* Clean up the code

* Remove InneLoopAreasProps from PR

* Add automation

* Update resources file

* Fix button visibility for automation

* Fix navigaiton buttons disappearing bug

* Update .idl file and add style as properties

* Add handlers for button visibility changes

* Add style handlers and update accessibility

* Add basic test with flipview

* Fix update of max number of pages

* Fix maxdisplayedpages onchange handler and address small PR issues

* remove commented code

* Update Naming

* Fix naming and fix pointer hover event

* Update Tests and leave some comments

* Update naming and tests

* Fix sv change size and override virtual methods

* Address PR comments

* Address PR issues

* Fix button not showing up on initial launch

* Clean up the code

* Update API tests

* Partially Update Tests

* Fix spacing

* Update Strings

* Attempt to fix tests

* Attempt to fix tests

* Fall back to manual scroll if fresh API is not available

* Move API check to SharedHelpers

* Fix naming

Co-authored-by: Ranjesh Jaganathan <28935693+ranjeshj@users.noreply.github.com>

* fix tests

* ImageIcon test fix

Co-authored-by: Keith Mahoney <41657372+kmahone@users.noreply.github.com>
Co-authored-by: Stephen L Peters <stpete@microsoft.com>
Co-authored-by: Marcel Wagner <marcel.alex.wagner@outlook.com>
Co-authored-by: Felix-Dev <FelixDev91@gmail.com>
Co-authored-by: Tony Xia <xia_tony@hotmail.com>
Co-authored-by: EJ <lalotahoma@icloud.com>
Co-authored-by: T Paine <30241445+teaP@users.noreply.github.com>
Co-authored-by: Jevan Saks <jevansa@microsoft.com>
Co-authored-by: Canhua Li <licanhua@live.com>
Co-authored-by: Ana Wishnoff <anawish@microsoft.com>
Co-authored-by: Morten Nielsen <1378165+dotMorten@users.noreply.github.com>
Co-authored-by: Thomas Claudius Huber <thomas@thomasclaudiushuber.com>
Co-authored-by: Luke Longley <18177025+llongley@users.noreply.github.com>
Co-authored-by: Vsevolod <sevkorobot@gmail.com>

* add missing PipsPager generatd file (#3755)

* Allow microsoft-ui-xaml to support multiple sets of styles (#3690)

* update customtask

* update project to use the customtool and support UseVisualStyle

* support new flag in api

* missing one file change for custombuild task

* update to new api and address some comments

* fix the ->

* script to move master xaml to v2.5 and add them to proj

* manually correct the missing items

* vcxproj back to UTF8

* standard the name and replace previous with 2dot5

* batch remove last line for project

* remove pips and address commentss

* trim last line

* remove newline at the end of file

* fix ##[error]dev\dll\XamlControlsResources.cpp(249,0): Error C26449: gsl::span or std::string_view created from a temporary will be invalid when the temporary is invalidated (gsl.view).

* remove return type in lambda

* remove Expander_v2.5.xaml, move merge.bat to tools and fix the test failure

* fix test

* Fix RadioButtons colouring bug (#3756)

* fix radioButtons colouring bug

* changes from comments

* Slider Visual Update (#3768)

* visual update

* re-add missing key

* add innerthumb size animation

* add colour transitions

* changes from comments

* colour transitions fix

* prepare for merge

* Update pfx and cer used for test signing (#3882)

* update pfx

* update CalendarView.xml master

* update default setting and codegen update
avoid crash on expander, reveal, NavView and progressbar

* resolve merge conflict

* enable test

* Fix the Latest still using 2.5 styles

Co-authored-by: T Paine <30241445+teaP@users.noreply.github.com>
Co-authored-by: Ranjesh <28935693+ranjeshj@users.noreply.github.com>
Co-authored-by: Keith Mahoney <41657372+kmahone@users.noreply.github.com>
Co-authored-by: Stephen L Peters <stpete@microsoft.com>
Co-authored-by: Marcel Wagner <marcel.alex.wagner@outlook.com>
Co-authored-by: Felix-Dev <FelixDev91@gmail.com>
Co-authored-by: Tony Xia <xia_tony@hotmail.com>
Co-authored-by: EJ <lalotahoma@icloud.com>
Co-authored-by: Jevan Saks <jevansa@microsoft.com>
Co-authored-by: Ana Wishnoff <anawish@microsoft.com>
Co-authored-by: Morten Nielsen <1378165+dotMorten@users.noreply.github.com>
Co-authored-by: Thomas Claudius Huber <thomas@thomasclaudiushuber.com>
Co-authored-by: Luke Longley <18177025+llongley@users.noreply.github.com>
Co-authored-by: Vsevolod <sevkorobot@gmail.com>
Co-authored-by: Karen Lai <7976322+karenbtlai@users.noreply.github.com>